# Generated by Django 3.1.1 on 2020-09-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0002_auto_20200919_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satker',
            name='kdsatker',
            field=models.CharField(max_length=8),
        ),
    ]
