# Generated by Django 3.1.1 on 2020-09-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0003_auto_20200919_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppk',
            old_name='kdsatker',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ppk',
            old_name='kdsatker_link',
            new_name='name_link',
        ),
        migrations.RenameField(
            model_name='satker',
            old_name='kdsatker',
            new_name='name',
        ),
    ]
