# Generated by Django 3.1.1 on 2020-09-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0005_transfer_satkers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppk',
            old_name='name_link',
            new_name='kdsatker',
        ),
        migrations.RenameField(
            model_name='satker',
            old_name='name',
            new_name='kdatker',
        ),
        migrations.RemoveField(
            model_name='ppk',
            name='name',
        ),
    ]
