# Generated by Django 3.1.1 on 2020-09-19 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0006_auto_20200919_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fnf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmfnf', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Kodeoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdoutput', models.CharField(max_length=3, unique=True)),
                ('nmkdoutput', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmks', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Satoutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsatoutcome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Satoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsatoutput', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sumberdana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumberdana', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sycmyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsycmyc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='satker',
            name='kdatker',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmgiat', models.CharField(max_length=4)),
                ('nmpaket', models.CharField(max_length=250)),
                ('pagurmp', models.FloatField(null=True)),
                ('trgoutput', models.DecimalField(decimal_places=3, max_digits=10)),
                ('trgoutcome', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('balai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.balai')),
                ('fnf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.fnf')),
                ('kdoutput', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.kodeoutput')),
                ('ks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.ks')),
                ('ppk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.ppk')),
                ('satker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.satker')),
                ('satoutcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.satoutcome')),
                ('satoutput', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.satoutput')),
                ('sumberdana', models.ManyToManyField(to='progresapp.Sumberdana')),
                ('sycmyc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.sycmyc')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.ta')),
                ('tag', models.ManyToManyField(to='progresapp.Tag')),
                ('wilayah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='progresapp.wilayah')),
            ],
        ),
    ]
