# Generated by Django 3.1.1 on 2020-09-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0007_auto_20200919_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paket',
            name='sumberdana',
        ),
        migrations.AddField(
            model_name='paket',
            name='phln',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='paket',
            name='sbsn',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Sumberdana',
        ),
    ]
