# Generated by Django 3.1.1 on 2020-09-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0008_auto_20200920_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='satoutcome',
            field=models.CharField(choices=[('m3/dtk', 'm3/dtk'), ('Dokumen', 'Dokumen'), ('Titik', 'Titik'), ('Buah', 'Buah'), ('Km', 'Km'), ('Ha', 'Ha'), ('Layanan', 'Layanan')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paket',
            name='satoutput',
            field=models.CharField(choices=[('Dokumen', 'Dokumen'), ('Titik', 'Titik'), ('Buah', 'Buah'), ('Km', 'Km'), ('Ha', 'Ha'), ('Layanan', 'Layanan')], max_length=25, null=True),
        ),
    ]
