# Generated by Django 3.1.1 on 2020-09-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0012_auto_20200920_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='trgoutcome',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='paket',
            name='trgoutput',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
    ]
