# Generated by Django 3.1.1 on 2020-09-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progresapp', '0013_auto_20200920_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paket',
            old_name='rmp',
            new_name='rpm',
        ),
    ]
